# OrcaVPN server config
[server]
# listen ip, default 0.0.0.0
ip = 0.0.0.0
# listen port, default 778
port = 778

# tun interface name
tun_name = orca-gate
# tun interface address
tun_addr = 10.80.80.1
# tun interface netmask
tun_mask = 255.255.255.0
# tun interface persist mode
tun_persist = off

# block enemy ip for ttl seconds, default disabled
block_ip_ttl = 60

# client sections
[clientX]
# private ip
ip = 10.80.80.2
# encryption key
key = 9f840f9cedc92e3968ef6c86cfc62f3400b1334a60e27799573d733b1038b28d
# encryption algorithm: xchacha20-poly1305|aes-hmac-sha1
cipher = xchacha20-poly1305
# enable internet access, default off
inet = on
# enable local network access, default off
lan = on
